import hashlib
import hmac
import json
import time
from decimal import Decimal, InvalidOperation

from django.conf import settings
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST

from hotel.models import Reservation, Guest, BusinessUnit, RoomType


def _verify_sonoga_signature(request, body):
    """
    Verify the HMAC signature generated by the WordPress connector.

    WordPress signs:

        timestamp + "." + body

    using:

        SONOGA_HMS_WEBHOOK_SECRET
    """

    secret = getattr(settings, "SONOGA_HMS_WEBHOOK_SECRET", "")

    if not secret:
        return False, "Webhook secret is not configured on Django."

    api_key = request.headers.get("X-Sonoga-Api-Key", "")
    timestamp = request.headers.get("X-Sonoga-Timestamp", "")
    supplied_signature = request.headers.get("X-Sonoga-Signature", "")

    if not api_key:
        return False, "Missing X-Sonoga-Api-Key."

    if not timestamp:
        return False, "Missing X-Sonoga-Timestamp."

    if not supplied_signature:
        return False, "Missing X-Sonoga-Signature."

    # API key must match the shared secret.
    if not hmac.compare_digest(api_key, secret):
        return False, "Invalid API key."

    # Prevent replay attacks.
    try:
        timestamp_int = int(timestamp)
    except ValueError:
        return False, "Invalid timestamp."

    current_time = int(time.time())

    if abs(current_time - timestamp_int) > 300:
        return False, "Request timestamp expired."

    message = f"{timestamp}.{body.decode('utf-8')}"

    expected_signature = hmac.new(
        secret.encode("utf-8"),
        message.encode("utf-8"),
        hashlib.sha256,
    ).hexdigest()

    expected_header = f"sha256={expected_signature}"

    if not hmac.compare_digest(
        supplied_signature,
        expected_header,
    ):
        return False, "Invalid webhook signature."

    return True, None


@csrf_exempt
@require_POST
def wp_booking_webhook(request):

    body = request.body

    # ---------------------------------------------------------
    # 1. Verify WordPress signature
    # ---------------------------------------------------------

    valid, error = _verify_sonoga_signature(request, body)

    if not valid:
        return JsonResponse(
            {
                "status": "error",
                "message": error,
            },
            status=401,
        )

    # ---------------------------------------------------------
    # 2. Decode JSON
    # ---------------------------------------------------------

    try:
        data = json.loads(body)
    except json.JSONDecodeError:
        return JsonResponse(
            {
                "status": "error",
                "message": "Invalid JSON payload.",
            },
            status=400,
        )

    # ---------------------------------------------------------
    # 3. Extract payload
    # ---------------------------------------------------------

    external_reference = str(
        data.get("external_reference", "")
    ).strip()

    business_unit_code = str(
        data.get("business_unit_code", "HOTEL")
    ).strip()

    room_type_code = str(
        data.get("room_type_code", "")
    ).strip()

    arrival_date = data.get("arrival_date")
    departure_date = data.get("departure_date")

    adults = data.get("adults", 1)
    children = data.get("children", 0)

    nightly_rate = data.get("nightly_rate", 0)
    discount_amount = data.get("discount_amount", 0)
    tax_amount = data.get("tax_amount", 0)

    status = str(
        data.get("status", "CONFIRMED")
    ).strip().upper()

    special_requests = str(
        data.get("special_requests", "")
    )

    guest_data = data.get("guest") or {}

    first_name = str(
        guest_data.get("first_name", "")
    ).strip()

    last_name = str(
        guest_data.get("last_name", "")
    ).strip()

    phone = str(
        guest_data.get("phone", "")
    ).strip()

    email = str(
        guest_data.get("email", "")
    ).strip()

    # ---------------------------------------------------------
    # 4. Validate required fields
    # ---------------------------------------------------------

    missing = []

    if not external_reference:
        missing.append("external_reference")

    if not room_type_code:
        missing.append("room_type_code")

    if not arrival_date:
        missing.append("arrival_date")

    if not departure_date:
        missing.append("departure_date")

    if not first_name:
        missing.append("guest.first_name")

    if not phone:
        missing.append("guest.phone")

    if missing:
        return JsonResponse(
            {
                "status": "error",
                "message": "Missing required fields.",
                "fields": missing,
            },
            status=400,
        )

    # ---------------------------------------------------------
    # 5. Convert numeric values
    # ---------------------------------------------------------

    try:
        nightly_rate = Decimal(str(nightly_rate or "0"))
        discount_amount = Decimal(
            str(discount_amount or "0")
        )
        tax_amount = Decimal(
            str(tax_amount or "0")
        )

        adults = int(adults or 1)
        children = int(children or 0)

    except (InvalidOperation, ValueError, TypeError):

        return JsonResponse(
            {
                "status": "error",
                "message": "Invalid numeric value in payload.",
            },
            status=400,
        )

    # ---------------------------------------------------------
    # 6. Find the hotel business unit
    # ---------------------------------------------------------

    unit = BusinessUnit.objects.filter(
        code=business_unit_code,
        is_active=True,
    ).first()

    if not unit:
        return JsonResponse(
            {
                "status": "error",
                "message": (
                    f'Active business unit "{business_unit_code}" '
                    "was not found."
                ),
            },
            status=400,
        )

    # ---------------------------------------------------------
    # 7. Find the room type
    # ---------------------------------------------------------

    room_type = RoomType.objects.filter(
        business_unit=unit,
        code=room_type_code,
        is_active=True,
    ).first()

    if not room_type:
        return JsonResponse(
            {
                "status": "error",
                "message": (
                    f'Room type "{room_type_code}" '
                    f'was not found for business unit '
                    f'"{business_unit_code}".'
                ),
            },
            status=400,
        )

    # ---------------------------------------------------------
    # 8. Find or create guest
    # ---------------------------------------------------------

    guest = None

    if email:
        guest = Guest.objects.filter(
            email__iexact=email
        ).first()

    if not guest:
        guest = Guest.objects.filter(
            phone=phone
        ).first()

    if guest:
        # Update missing/new guest information.
        guest.first_name = first_name
        guest.last_name = last_name
        guest.phone = phone

        if email:
            guest.email = email

        guest.save()

    else:
        guest = Guest.objects.create(
            first_name=first_name,
            last_name=last_name,
            phone=phone,
            email=email,
        )

    # ---------------------------------------------------------
    # 9. Convert status
    # ---------------------------------------------------------

    valid_statuses = {
        Reservation.Status.PENDING,
        Reservation.Status.CONFIRMED,
        Reservation.Status.CANCELLED,
        Reservation.Status.NO_SHOW,
        Reservation.Status.CHECKED_IN,
        Reservation.Status.CHECKED_OUT,
    }

    if status not in valid_statuses:
        status = Reservation.Status.CONFIRMED

    # ---------------------------------------------------------
    # 10. Create/update reservation
    # ---------------------------------------------------------

    reservation = Reservation.objects.filter(
        source=Reservation.Source.WORDPRESS,
        external_reference=external_reference,
    ).first()

    if reservation:

        reservation.business_unit = unit
        reservation.guest = guest
        reservation.room_type = room_type
        reservation.arrival_date = arrival_date
        reservation.departure_date = departure_date
        reservation.adults = adults
        reservation.children = children
        reservation.nightly_rate = nightly_rate
        reservation.discount_amount = discount_amount
        reservation.tax_amount = tax_amount
        reservation.status = status
        reservation.special_requests = special_requests

        reservation.save()

        created = False

    else:

        reservation = Reservation.objects.create(
            business_unit=unit,
            reservation_number=(
                f"WEB-{external_reference}"
            )[:40],
            external_reference=external_reference,
            source=Reservation.Source.WORDPRESS,
            guest=guest,
            room_type=room_type,
            arrival_date=arrival_date,
            departure_date=departure_date,
            adults=adults,
            children=children,
            nightly_rate=nightly_rate,
            discount_amount=discount_amount,
            tax_amount=tax_amount,
            status=status,
            special_requests=special_requests,
        )

        created = True

    # ---------------------------------------------------------
    # 11. Return success
    # ---------------------------------------------------------

    return JsonResponse(
        {
            "status": "success",
            "message": (
                "Booking created successfully."
                if created
                else "Booking updated successfully."
            ),
            "reservation_id": reservation.id,
            "reservation_number": reservation.reservation_number,
            "external_reference": reservation.external_reference,
            "created": created,
        },
        status=201 if created else 200,
    )