services:
  - type: web
    name: sonoga-hms
    runtime: docker
    plan: free
    region: singapore

    dockerfilePath: ./Dockerfile

    healthCheckPath: /health/

    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true

      - key: DJANGO_DEBUG
        value: "False"

      - key: DJANGO_ALLOWED_HOSTS
        value: "sonoga-hms.onrender.com,manage.sonogahotels.com,www.manage.sonogahotels.com"

      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: "https://sonoga-hms.onrender.com,https://manage.sonogahotels.com,https://www.manage.sonogahotels.com"

      - key: POSTGRES_DB
        sync: false

      - key: POSTGRES_USER
        sync: false

      - key: POSTGRES_PASSWORD
        sync: false

      - key: POSTGRES_HOST
        sync: false

      - key: POSTGRES_PORT
        value: "5432"