services:
  - type: web
    name: sonoga-hms
    runtime: docker
    plan: free
    region: frankfurt

    dockerfilePath: ./Dockerfile

    healthCheckPath: /health/

    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true

      - key: DJANGO_DEBUG
        value: "False"

      - key: DJANGO_ALLOWED_HOSTS
        value: "sonoga-hms.onrender.com,manage.sonogahotels.com,www.manage.sonogahotels.com"

      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: "https://sonoga-hms.onrender.com,https://manage.sonogahotels.com,https://www.manage.sonogahotels.com"

      - key: POSTGRES_DB
        fromDatabase:
          name: sonoga-hms-db
          property: database

      - key: POSTGRES_USER
        fromDatabase:
          name: sonoga-hms-db
          property: user

      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: sonoga-hms-db
          property: password

      - key: POSTGRES_HOST
        fromDatabase:
          name: sonoga-hms-db
          property: host

      - key: POSTGRES_PORT
        fromDatabase:
          name: sonoga-hms-db
          property: port
