# Generated by Django 5.2.17 on 2026-08-22 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['department__name', 'name']},
        ),
        migrations.RemoveConstraint(
            model_name='position',
            name='uniq_position_name_per_department',
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='organization.department'),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='unit_type',
            field=models.CharField(choices=[('HEAD_OFFICE', 'Head Office'), ('HOTEL', 'Sonoga Hotels'), ('WATER', 'Pure Water Factory'), ('BREAD', 'Bread Factory'), ('ENERGY', 'Crown Field Energy'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='position',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='organization.businessunit'),
        ),
        migrations.AlterField(
            model_name='position',
            name='reports_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinate_positions', to='organization.position'),
        ),
    ]
