# Generated by Django 6.0.8 on 2026-08-17 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
        ('inventory', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=150)),
                ('product_family', models.CharField(choices=[('WATER', 'Water'), ('BREAD', 'Bread / Bakery')], max_length=20)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('wholesale_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('standard_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('shelf_life_days', models.PositiveIntegerField(blank=True, null=True)),
                ('minimum_stock', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factory_products', to='organization.businessunit')),
                ('inventory_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='factory_product', to='inventory.item')),
            ],
            options={
                'ordering': ['business_unit__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('production_date', models.DateField()),
                ('shift', models.CharField(blank=True, max_length=60)),
                ('planned_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('produced_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('rejected_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('accepted_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PRODUCTION', 'In Production'), ('COMPLETED', 'Completed'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_production_batches', to=settings.AUTH_USER_MODEL)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_batches', to='organization.businessunit')),
                ('finished_goods_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_output_batches', to='inventory.store')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_batches', to='factory.factoryproduct')),
                ('raw_material_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_material_batches', to='inventory.store')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervised_production_batches', to='hr.employee')),
            ],
            options={
                'ordering': ['-production_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loss_type', models.CharField(choices=[('REJECT', 'Production Reject'), ('DAMAGE', 'Damage'), ('EXPIRY', 'Expiry'), ('RETURN_WRITE_OFF', 'Returned Product Write-off'), ('OTHER', 'Other')], max_length=30)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('reason', models.TextField()),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factory_losses_recorded', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='losses', to='factory.productionbatch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionMaterialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_usages', to='factory.productionbatch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_usages', to='inventory.item')),
            ],
            options={
                'ordering': ['batch', 'item__name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('output_quantity', models.DecimalField(decimal_places=3, default=1, max_digits=14)),
                ('is_default', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='factory.factoryproduct')),
            ],
            options={
                'ordering': ['product__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_batches', to='factory.recipe'),
        ),
        migrations.CreateModel(
            name='RecipeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_lines', to='inventory.item')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='factory.recipe')),
            ],
            options={
                'ordering': ['recipe', 'item__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='factoryproduct',
            constraint=models.UniqueConstraint(fields=('business_unit', 'code'), name='uniq_factory_product_code_per_unit'),
        ),
        migrations.AddConstraint(
            model_name='factoryproduct',
            constraint=models.UniqueConstraint(fields=('business_unit', 'name'), name='uniq_factory_product_name_per_unit'),
        ),
        migrations.AddConstraint(
            model_name='productionmaterialusage',
            constraint=models.UniqueConstraint(fields=('batch', 'item'), name='uniq_material_per_batch'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('product', 'name'), name='uniq_recipe_name_per_product'),
        ),
        migrations.AddIndex(
            model_name='productionbatch',
            index=models.Index(fields=['business_unit', 'production_date', 'status'], name='factory_pro_busines_d7a0ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='recipeline',
            constraint=models.UniqueConstraint(fields=('recipe', 'item'), name='uniq_recipe_item'),
        ),
    ]
