# Generated by Django 5.2.17 on 2026-08-22 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('production_date', models.DateField()),
                ('shift', models.CharField(blank=True, max_length=60)),
                ('planned_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('produced_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('rejected_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('accepted_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PRODUCTION', 'In Production'), ('COMPLETED', 'Completed'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-production_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionMaterialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['batch', 'item__name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('output_quantity', models.DecimalField(decimal_places=3, default=1, max_digits=14)),
                ('is_default', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['product__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['recipe', 'item__name'],
            },
        ),
        migrations.CreateModel(
            name='BatchLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loss_type', models.CharField(choices=[('REJECT', 'Production Reject'), ('DAMAGE', 'Damage'), ('EXPIRY', 'Expiry'), ('RETURN_WRITE_OFF', 'Returned Product Write-off'), ('OTHER', 'Other')], max_length=30)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('reason', models.TextField()),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factory_losses_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FactoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=150)),
                ('product_family', models.CharField(choices=[('WATER', 'Water'), ('BREAD', 'Bread / Bakery')], max_length=20)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('wholesale_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('standard_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('shelf_life_days', models.PositiveIntegerField(blank=True, null=True)),
                ('minimum_stock', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factory_products', to='organization.businessunit')),
            ],
            options={
                'ordering': ['business_unit__name', 'name'],
            },
        ),
    ]
