# Generated by Django 5.2.17 on 2026-08-22 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory', '0001_initial'),
        ('hr', '__first__'),
        ('inventory', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='factoryproduct',
            name='inventory_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='factory_product', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_production_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='business_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_batches', to='organization.businessunit'),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='finished_goods_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_output_batches', to='inventory.store'),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_batches', to='factory.factoryproduct'),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='raw_material_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_material_batches', to='inventory.store'),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervised_production_batches', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='batchloss',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='losses', to='factory.productionbatch'),
        ),
        migrations.AddField(
            model_name='productionmaterialusage',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_usages', to='factory.productionbatch'),
        ),
        migrations.AddField(
            model_name='productionmaterialusage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_usages', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='factory.factoryproduct'),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_batches', to='factory.recipe'),
        ),
        migrations.AddField(
            model_name='recipeline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_lines', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='recipeline',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='factory.recipe'),
        ),
        migrations.AddConstraint(
            model_name='factoryproduct',
            constraint=models.UniqueConstraint(fields=('business_unit', 'code'), name='uniq_factory_product_code_per_unit'),
        ),
        migrations.AddConstraint(
            model_name='factoryproduct',
            constraint=models.UniqueConstraint(fields=('business_unit', 'name'), name='uniq_factory_product_name_per_unit'),
        ),
        migrations.AddConstraint(
            model_name='productionmaterialusage',
            constraint=models.UniqueConstraint(fields=('batch', 'item'), name='uniq_material_per_batch'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('product', 'name'), name='uniq_recipe_name_per_product'),
        ),
        migrations.AddIndex(
            model_name='productionbatch',
            index=models.Index(fields=['business_unit', 'production_date', 'status'], name='factory_pro_busines_d7a0ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='recipeline',
            constraint=models.UniqueConstraint(fields=('recipe', 'item'), name='uniq_recipe_item'),
        ),
    ]
