# Generated by Django 6.0.8 on 2026-08-17 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_number', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=80)),
                ('middle_name', models.CharField(blank=True, max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('employment_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('CONTRACT', 'Contract'), ('CASUAL', 'Casual'), ('TEMPORARY', 'Temporary')], default='PERMANENT', max_length=20)),
                ('employment_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('SUSPENDED', 'Suspended'), ('RESIGNED', 'Resigned'), ('TERMINATED', 'Terminated'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=20)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('account_name', models.CharField(blank=True, max_length=150)),
                ('account_number', models.CharField(blank=True, max_length=30)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organization.businessunit')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organization.department')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organization.position')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='hr.employee')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
