# Generated by Django 5.2.17 on 2026-08-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='staff_number',
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
    ]
