# Generated by Django 5.2.17 on 2026-08-22 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('RAW_MATERIAL', 'Raw Material'), ('FINISHED_PRODUCT', 'Finished Product'), ('PACKAGING', 'Packaging'), ('CONSUMABLE', 'Consumable'), ('FOOD', 'Food'), ('DRINK', 'Drink'), ('LINEN', 'Linen'), ('CLEANING', 'Cleaning'), ('MAINTENANCE', 'Maintenance'), ('OTHER', 'Other')], max_length=30)),
                ('unit', models.CharField(choices=[('PIECE', 'Piece'), ('BAG', 'Bag'), ('CARTON', 'Carton'), ('ROLL', 'Roll'), ('KG', 'Kilogram'), ('GRAM', 'Gram'), ('LITRE', 'Litre'), ('ML', 'Millilitre'), ('PACK', 'Pack'), ('LOAF', 'Loaf'), ('DOZEN', 'Dozen'), ('UNIT', 'Unit')], default='UNIT', max_length=20)),
                ('standard_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('minimum_stock', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('reorder_level', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='organization.businessunit')),
            ],
            options={
                'ordering': ['business_unit__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('store_type', models.CharField(choices=[('RAW_MATERIAL', 'Raw Material'), ('FINISHED_GOODS', 'Finished Goods'), ('GENERAL', 'General'), ('KITCHEN', 'Kitchen'), ('BAR', 'Bar'), ('HOUSEKEEPING', 'Housekeeping'), ('MAINTENANCE', 'Maintenance')], default='GENERAL', max_length=30)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='organization.businessunit')),
            ],
            options={
                'ordering': ['business_unit__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out')], max_length=10)),
                ('movement_type', models.CharField(choices=[('OPENING', 'Opening Balance'), ('PURCHASE', 'Purchase / Goods Receipt'), ('PRODUCTION_ISSUE', 'Production Material Issue'), ('PRODUCTION_OUTPUT', 'Production Output'), ('SALE', 'Sale'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('RETURN_IN', 'Customer Return In'), ('RETURN_OUT', 'Supplier Return Out'), ('DAMAGE', 'Damage / Write-off'), ('EXPIRY', 'Expiry / Wastage'), ('ADJUSTMENT_IN', 'Adjustment In'), ('ADJUSTMENT_OUT', 'Adjustment Out')], max_length=30)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_void', models.BooleanField(default=False)),
                ('void_reason', models.CharField(blank=True, max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.item')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements_posted', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('business_unit', 'code'), name='uniq_item_code_per_unit'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('business_unit', 'name'), name='uniq_item_name_per_unit'),
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.UniqueConstraint(fields=('business_unit', 'code'), name='uniq_store_code_per_unit'),
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.UniqueConstraint(fields=('business_unit', 'name'), name='uniq_store_name_per_unit'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['store', 'item', 'created_at'], name='inventory_s_store_i_f2259e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference'], name='inventory_s_referen_16defd_idx'),
        ),
    ]
