# Generated by Django 5.2.17 on 2026-08-22 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commercial', '0001_initial'),
        ('factory', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_lines', to='factory.factoryproduct'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='commercial.distributionroute'),
        ),
        migrations.AddField(
            model_name='factorypayment',
            name='received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factory_payments_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productreturn',
            name='business_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_returns', to='organization.businessunit'),
        ),
        migrations.AddField(
            model_name='productreturn',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_returns', to='commercial.customer'),
        ),
        migrations.AddField(
            model_name='productreturn',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='factory.factoryproduct'),
        ),
        migrations.AddField(
            model_name='productreturn',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factory_returns_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='business_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='organization.businessunit'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factory_sales_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='commercial.customer'),
        ),
    ]
