# Generated by Django 5.2.17 on 2026-08-22 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commercial', '0002_initial'),
        ('factory', '0001_initial'),
        ('hr', '__first__'),
        ('inventory', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='fulfillment_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='inventory.store'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='salesperson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='productreturn',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='commercial.salesinvoice'),
        ),
        migrations.AddField(
            model_name='factorypayment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='commercial.salesinvoice'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='commercial.salesinvoice'),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='commercial.salesinvoice'),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_lines', to='factory.factoryproduct'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='business_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='organization.businessunit'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='commercial.vehicle'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['business_unit', 'invoice_date', 'status'], name='commercial__busines_6ee7a4_idx'),
        ),
    ]
